const mongoose = require('mongoose');

const galleryItemSchema = new mongoose.Schema({
    title: { type: String, required: true, trim: true },
    locationTag: { type: String, required: true, trim: true }, // e.g., "Pokhara", "Everest Base Camp"
    description: { type: String },

    // Media details
    mediaUrl: { type: String, required: true },
    thumbnailUrl: { type: String, default: null }, // HD thumbnail generated by browser canvas
    fileType: { type: String, enum: ['image', 'video'], required: true },
    aspectRatio: { type: String, enum: ['landscape', 'portrait'], default: 'landscape' },
    views: { type: Number, default: 0 },

    // Visibility
    isActive: { type: Boolean, default: true }
}, { timestamps: true });

module.exports = mongoose.model('GalleryItem', galleryItemSchema);